# Generated by Django 3.1 on 2020-08-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200818_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='family',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='person',
            name='second_name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
