# Generated by Django 3.1 on 2020-09-01 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200831_2041'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('name', 'second_name', 'family')},
        ),
    ]
