# Generated by Django 3.1 on 2020-09-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200904_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='event', to='core.Person'),
        ),
    ]
