# Generated by Django 3.1 on 2020-09-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200904_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='family',
            field=models.CharField(blank=True, max_length=300, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='second_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Отчество'),
        ),
    ]
