# Generated by Django 3.1 on 2020-09-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200905_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='adress',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='adress',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
    ]
