# Generated by Django 3.1 on 2020-09-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200906_1402'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('name', 'family')},
        ),
    ]
