# Generated by Django 3.1 on 2020-09-07 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200907_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['family', 'name'], 'verbose_name': 'Person'},
        ),
    ]
