# Generated by Django 3.1 on 2020-09-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200908_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=100, verbose_name='Псевдоним'),
        ),
    ]
