# Generated by Django 4.2.1 on 2024-08-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201126_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='viaf_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VIAF ID'),
        ),
        migrations.AddField(
            model_name='person',
            name='viaf_id_alternative',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VIAF ID'),
        ),
        migrations.AddField(
            model_name='person',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Wikidata ID'),
        ),
    ]
